language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4lab
  api_key:
    secure: gn0yimYtSbddz9dlAwQVQXN0lHhqRra4IFoezbeinMtLNdpBB5DIADGA3Efeun+7VGplof7LIb/zYuwWAEx8Nu4QVrfoWskTImNQNPYt65YpGVvLK/gpsnXLBzYI8engerRh/VELuI/IVOsKuvr9h1Evjw3XeWFOpf9BmtJpgis6nN41CXSQoz3tduALp2GrP3miYUEhwPbHgTw8pog9yS7lxkbLe+ibNp14uDrSzZ5Eqp0sqT9MvtUVNFfVY9Vd38phtbzGMKSld4uZUPVQcvUJ8hqEC1SHp1BYboIftT7OHMJi5bG3RZZiPhn6Yv+lCrfqObiKCmpYHHakTgQBl8SfCPbfO3+Z6YY8Y2gt0cor8lSY4nJw5+mNlrsguSwO6i8WNCHBGZpQoUswpmoBiZlGHxTkrtbtP25R1T0JFfB9vHcVxbt91AYlXRPHOhogVwCS5VBDRG+dGGjEYZRFBreNpJxTFCK1dGRT51XYrzTxsG2ogFlyXLmZyVSQDyO5a9Gynmriqt2e0igAIf8R0nKzE/XvBm6GfLNXt9mo9ups1Qw9AIUL6SroukXsN/vlVE//kHbMOJ+30mirX0cimIHA19E/Zy/tf9NauyPSFYMhpCT2ynWSsQyJ7WtgFowGNanxqOzCB1JTG9jLW9jYBFPNvOCKGSdnmCG9FnZcp/k=
